# Site
name: "Mehrdad's Data Insights"
title: "Mehrdad Touraji - Data & Tech Exploration"
description: "A blog about data engineering, software development, and my journey through technology."
logo: 'assets/images/mehrdad-logo.png'  # Update with your logo
favicon: 'assets/images/mehrdad-favicon.png'  # Update with your favicon
google_analytics: 'UA-xxxxxxxx-1'  # Your Google Analytics ID
disqus: 'mehrdadblog'  # Your Disqus shortname
mailchimp-list: ''  # Your Mailchimp list, if applicable
include: ["_pages"]
permalink: /:title/
email: mehrdad.touraji@gmail.com

# Authors
# Authors
authors:
  mehrdad:
    name: Mehrdad
    display_name: Mehrdad Touraji
    avatar: 'assets/images/mehrdad.jpg'  # Update with your image
    email: mehrdad.touraji@gmail.com
    web: https://mtouraji.streamlit.app/
    twitter: https://twitter.com/yourtwitter  # Your Twitter
    description: "Data engineer, software developer, and tech enthusiast. Exploring the intersection of data and decision-making."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
